# Generated by Django 5.2 on 2025-04-12 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_trainee_fixed_session_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='fixed_session_days',
        ),
        migrations.CreateModel(
            name='FixedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('SA', 'Saturday'), ('SU', 'Sunday'), ('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday')], max_length=2)),
                ('location', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_sessions', to='accounts.trainee')),
            ],
        ),
    ]
