# Generated by Django 5.2 on 2025-04-12 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('xp_reward', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('warmup', 'Warm-Up & Movement'), ('groundstroke', 'Groundstroke Drill'), ('target', 'Target Drill'), ('power', 'Power & Consistency'), ('serve', 'Serve Drill'), ('tactical', 'Tactical/Pattern Drill'), ('fitness', 'Fitness Drill'), ('situational', 'Situational Drill'), ('solo', 'Solo/Wall Drill'), ('custom', 'Custom Drill')], max_length=50)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned', to='accounts.trainee')),
            ],
        ),
    ]
