# Generated by Django 5.2 on 2025-04-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
