# Generated by Django 5.2 on 2025-04-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='achievements',
            field=models.ManyToManyField(blank=True, through='gamification.PlayerBadge', to='gamification.badge'),
        ),
    ]
