# Generated by Django 5.2 on 2025-04-13 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_playerprofile_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gamification.level'),
            preserve_default=False,
        ),
    ]
